# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FiskerGallery' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'SVProgressHUD'
  target 'FiskerGalleryTests' do
    # Pods for testing
  end

end

target 'FiskerGalleryiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'SVProgressHUD'
  # Pods for FiskerGalleryiOS

  target 'FiskerGalleryiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
